"""drop resume_filename from users

Revision ID: 39a738bd5a55
Revises: 860b1ad51da5
Create Date: 2026-02-12 13:21:48.733861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a738bd5a55'
down_revision: Union[str, Sequence[str], None] = '860b1ad51da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_filename', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
