"""initial schema: users, jobs, job_global_stats

Revision ID: c1e1c1b36d56
Revises:
Create Date: 2026-02-12 12:11:06.109133

Ensures pgcrypto is available so gen_random_uuid() works on all supported
Postgres versions (PG 13+ has it built-in; pgcrypto provides it on older).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e1c1b36d56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure gen_random_uuid() is available (PG 13+ has it built-in; pgcrypto on older)
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pgcrypto"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_global_stats',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('resume_latex', sa.Text(), nullable=True),
    sa.Column('resume_filename', sa.String(length=512), nullable=True),
    sa.Column('max_iterations', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('target_pages', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_bullet_lines', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('original_latex', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(length=512), nullable=True),
    sa.Column('target_pages', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_iterations', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('max_bullet_lines', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('restart_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_restart_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('optimized_latex', sa.Text(), nullable=True),
    sa.Column('result_filename', sa.String(length=512), nullable=True),
    sa.Column('optimized_latex_available', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('original_latex_length', sa.Integer(), nullable=True),
    sa.Column('optimized_latex_length', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the singleton stats row
    op.execute(
        sa.text(
            "INSERT INTO job_global_stats (id, processed, completed, failed) "
            "VALUES (1, 0, 0, 0) ON CONFLICT (id) DO NOTHING"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_created_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('job_global_stats')
    # ### end Alembic commands ###
